git_account_name = "your-git-account"
git_branch_name = "your-git-branch"
git_repository_name = "your-git-repository"
git_root_folder = "/datafactory"
git_root_synapse_folder = "/synapse"
git_url = "https://github.com"